import Button from "@/components/ui/Button"
import Marquee from "@/components/ui/Marquee"
import { FaArrowRight, FaRegEyeSlash, FaRegUser } from "react-icons/fa6";
import { RiUserSmileLine, RiStarSmileLine, RiDiamondLine, RiAlignLeft, RiBracesFill, RiForbid2Line, RiPuzzle2Line, RiFlashlightLine, RiGitRepositoryPrivateLine } from "react-icons/ri";
import { TbDental } from "react-icons/tb";
import { LuLayers, LuCrown, LuAnchor, LuFlaskConical } from "react-icons/lu";
import { IoLink } from "react-icons/io5";
import { VscSparkle } from "react-icons/vsc";
import { FiShield, FiDroplet } from "react-icons/fi";
import { GoDash } from "react-icons/go";
import { PiWarningCircleLight } from "react-icons/pi";
import { BiShieldPlus, BiLeaf } from "react-icons/bi";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Our-Services | Raviraj Dental Clinic",
    description: "Generated by create next app",
};



const page = () => {
    const treatments = [
        {
            id: "01",
            mainTitle: "Preventive Dentistry",
            mainContent:
                "Regular checkups, professional cleanings, and early diagnosis help maintain oral health, prevent cavities, gum disease, and ensure long-term healthy teeth.",

            children: [
                {
                    subTitle: "Dental check-ups & oral exams",
                    subContent:
                        "Regular dental checkups and oral exams help detect problems early and keep your teeth and gums healthy.",
                    subIcon: <RiUserSmileLine size={20} />,
                },

                {
                    subTitle: "Teeth cleaning",
                    subContent:
                        "keep your smile fresh and healthy with gentle, thorough teeth cleaning performed by our experts.",
                    subIcon: <TbDental size={20} />,
                },
            ],
        },

        {
            id: "02",
            mainTitle: "Restorative Dentistry",
            mainContent:
                "Repairs damaged or missing teeth using fillings, crowns, bridges, and dentures to restore function, strength, and natural appearance of your smile.",

            children: [
                {
                    subTitle: "Dental fillings",
                    subContent:
                        "Dental fillings restore damaged or decayed teeth, helping protect them and maintain their function.",
                    subIcon: <LuLayers size={20} />,
                },

                {
                    subTitle: "Dental crowns",
                    subContent:
                        "Dental crowns restore and protect damaged teeth, improving their strength and appearance.",
                    subIcon: <LuCrown size={20} />,
                },

                {
                    subTitle: "Bridges",
                    subContent:
                        "Our dental bridges are designed to replace one or more missing teeth, improving both function and appearance.",
                    subIcon: <IoLink size={20} />,
                },

                {
                    subTitle: "Dentures (full & partial)",
                    subContent:
                        "Restore your smile with comfortable dentures that help you eat, speak, and smile confidently.",
                    subIcon: <RiStarSmileLine size={20} />,
                },
            ],
        },

        {
            id: "03",
            mainTitle: "Cosmetic Dentistry",
            mainContent:
                "Enhances the appearance of your smile through whitening, veneers, bonding, and other treatments for brighter, more attractive, and confident-looking teeth.",

            children: [
                {
                    subTitle: "Teeth whitening",
                    subContent:
                        "Brighten your smile with safe and effective professional teeth whitening for a more confident and radiant look.",
                    subIcon: <VscSparkle size={20} />,
                },

                {
                    subTitle: "Dental veneers",
                    subContent:
                        "Enhance your smile with custom-made veneers designed to improve the shape, color, and appearance of your teeth.",
                    subIcon: <RiDiamondLine size={20} />,
                },
            ],
        },

        {
            id: "04",
            mainTitle: "Orthodontics",
            mainContent:
                "Straightens teeth and corrects bite issues using braces, aligners, and retainers to improve alignment, function, and overall smile appearance.",

            children: [
                {
                    subTitle: "Metal braces",
                    subContent:
                        "Straighten your teeth effectively with durable and reliable metal braces for a well-aligned smile.",
                    subIcon: <RiAlignLeft size={20} />,
                },

                {
                    subTitle: "Ceramic braces",
                    subContent:
                        "Straighten your teeth with less noticeable ceramic braces designed for comfort and aesthetics.",
                    subIcon: <RiBracesFill size={20} />,
                },

                {
                    subTitle: "Clear aligners (Invisible)",
                    subContent:
                        "Straighten your teeth with clear, removable aligners that are comfortable and nearly invisible.",
                    subIcon: <FaRegEyeSlash size={20} />,
                },

                {
                    subTitle: "Retainers",
                    subContent:
                        "Maintain your newly aligned smile with custom retainers designed to keep your teeth in place.",
                    subIcon: <RiGitRepositoryPrivateLine size={20} />,
                },
            ],
        },

        {
            id: "05",
            mainTitle: "Endodontics",
            mainContent:
                "Treats infections inside the tooth using root canal procedures to relieve pain, remove infection, and preserve the natural tooth structure.",

            children: [
                {
                    subTitle: "Root canal treatment",
                    subContent:
                        "Root canal therapy removes infection from inside the tooth and restores its health and function.",
                    subIcon: <FiShield size={20} />,
                },

                {
                    subTitle: "Apicoectomy (root-end surgery)",
                    subContent:
                        "Targeted treatment to eliminate infection and protect your tooth when other procedures aren’t enough.",
                    subIcon: <RiForbid2Line size={20} />,
                },
            ],
        },

        {
            id: "06",
            mainTitle: "Oral Surgery / Implantology",
            mainContent:
                "Performs surgical treatments including tooth extractions and dental implants to restore function, replace missing teeth, and improve oral health.",

            children: [
                {
                    subTitle: "Dental implants",
                    subContent:
                        "Replace missing teeth with strong, natural-looking dental implants for a permanent solution.",
                    subIcon: <LuAnchor size={20} />,
                },

                {
                    subTitle: "Tooth extraction",
                    subContent:
                        "We perform simple and surgical extractions with care to ensure comfort and quick recovery.",
                    subIcon: <GoDash size={20} />,
                },

                {
                    subTitle: "Wisdom teeth removal",
                    subContent:
                        "Safe and effective removal of wisdom teeth to relieve pain and prevent future dental issues.",
                    subIcon: <PiWarningCircleLight size={20} />,
                },

                {
                    subTitle: "Bone grafting",
                    subContent:
                        "Strengthen your jawbone with advanced grafting procedures for better support and healing.",
                    subIcon: <RiPuzzle2Line size={20} />,
                },
            ],
        },

        {
            id: "07",
            mainTitle: "Periodontics",
            mainContent:
                "Focuses on treating gum disease and supporting structures through deep cleaning and surgical procedures to maintain healthy gums and prevent tooth loss.",

            children: [
                {
                    subTitle: "Scaling & root planing",
                    subContent:
                        "Deep cleaning treatment that removes plaque and tartar from below the gum line to improve gum health.",
                    subIcon: <FiDroplet size={20} />,
                },

                {
                    subTitle: "Gum disease treatment",
                    subContent:
                        "Effective treatment to control gum infection, reduce inflammation, and restore healthy gums.",
                    subIcon: <BiShieldPlus size={20} />,
                },

                {
                    subTitle: "Gum grafting",
                    subContent:
                        "Gum grafting treatment restores receding gums, protects tooth roots, and improves overall gum health and appearance.",
                    subIcon: <BiLeaf size={20} />,
                },

                {
                    subTitle: "Laser gum therapy",
                    subContent:
                        "Advanced laser treatment that removes infected tissue, reduces bacteria, and promotes faster gum healing.",
                    subIcon: <RiFlashlightLine size={20} />,
                },
            ],
        },

        {
            id: "08",
            mainTitle: "Pediatric Dentistry",
            mainContent:
                "Provides specialized dental care for children, focusing on prevention, early treatment, and healthy habits to ensure strong teeth and proper oral development.",

            children: [
                {
                    subTitle: "Child dental checkups",
                    subContent:
                        "Gentle dental checkups for children to monitor oral health and ensure healthy smile development.",
                    subIcon: <FaRegUser size={20} />,
                },

                {
                    subTitle: "Fluoride Treatments",
                    subContent:
                        "Fluoride treatment strengthens tooth enamel and helps protect children’s teeth from cavities and decay.",
                    subIcon: <LuFlaskConical size={20} />,
                },
            ],
        },
    ]
    return (
        <section>
            <div className="w-full h-130 bg-black pt-10">
                <h1 className="text-center font-heading font-medium sm:text-[40px] text-[30px] text-white pt-15 flex flex-col"><span className="text-[#072959]">Our</span>  Dental Services</h1>
                <p className="font-heading sm:text-[14px] text-[12px]   text-center text-[#8D9EB7]">Comprehensive care for a healthy, confident smile.</p>
                <div className="flex items-center flex-col gap-5 justify-center mt-18">
                    <p className="font-heading sm:text-[14px] text-[12px] sm:w-175 w-auto px-2 sm:px-0 text-center text-[#8D9EB7]">We provide high-quality dental care with a focus on comfort, hygiene, and long-lasting results. Our experienced team is dedicated to helping you achieve a healthy and confident smile.</p>
                    <Button className="bg-[#072959] text text-white flex gap-1" size="sm">Request Consultation <FaArrowRight />  </Button>
                </div>
            </div>
            <Marquee />
            <div className="w-full bg-white  sm:px-20 px-8 sm:py-10 py-8">
                <div className="pt-15 space-y-1">
                    <p className="text-center font-heading font-normal sm:text-[12px] text-[10px]">WHAT WE OFFER</p>
                    <h2 className="text-center flex flex-col font-heading font-medium sm:text-[33px] text-[23px]">Treatments We <span className="text-[#072959]">Specialize In </span></h2>
                </div>
                <div className="flex flex-col gap-20 mt-10">
                    {treatments.map((treatment) => (
                        <div
                            key={treatment.id}
                            className="flex flex-col lg:flex-row justify-between items-start gap-8 lg:gap-12">
                            {/* Left Side */}
                            <div className="lg:w-[30%] w-full">
                                <div className="sm:-space-y-px">
                                    <span className="font-heading font-semibold sm:text-[59px] text-[47px] text-[#E6EAEF]">
                                        {treatment.id}
                                    </span>

                                    <h3 className="font-heading font-medium sm:text-[19px] text-[16px]">
                                        {treatment.mainTitle}
                                    </h3>

                                    <p className="font-body font-normal sm:text-[14px] text-[13px] text-[#4C4B48]">
                                        {treatment.mainContent}
                                    </p>
                                </div>
                            </div>

                            {/* Right Side */}
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 lg:w-[65%] w-full">
                                {treatment.children.map((subtreatment, idx) => (
                                    <div
                                        key={idx}
                                        className="border border-[#E6EAEF] sm:p-5 p-3 h-full">
                                        <span className="sm:w-12 w-10 sm:h-9.5 h-7.5 rounded-md flex items-center justify-center bg-[#E6EAEF] text-[#072959]">
                                            {subtreatment.subIcon}
                                        </span>

                                        <h3 className="font-heading font-medium sm:text-[19px] text-[16px] mt-3">
                                            {subtreatment.subTitle}
                                        </h3>

                                        <p className="font-body font-normal sm:text-[14px] text-[13px] text-[#4C4B48] mt-2">
                                            {subtreatment.subContent}
                                        </p>
                                    </div>
                                ))}
                            </div>

                        </div>

                    ))}
                </div>
            </div>

        </section>
    )
}

export default page
